FROM jboss/wildfly:25.0.0.Final

# Deploy your WAR into WildFly
COPY target/jakartaee8-starter.war /opt/jboss/wildfly/standalone/deployments/jakartaee8-starter.war

# Expose WildFly default port
EXPOSE 8080

# Start WildFly
CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0"]